package com.example.cs481app.data

import com.google.firebase.Firebase
import com.google.firebase.auth.auth
import com.google.firebase.firestore.firestore
import kotlinx.coroutines.tasks.await

//firestore handler
//going to handle all the read and write operations for the incident records

object FirestoreHandler {

    private val db = Firebase.firestore
    private val auth = Firebase.auth

    // Get current user's UID
    private fun getCurrentUID(): String {
        return auth.currentUser?.uid
            ?: throw IllegalStateException("No user is currently logged in.")
    }

    //save incident
    //saves a new incident to firestore
    suspend fun saveIncident(incident: Incident): String {
        val uid = getCurrentUID()

        return try {
            val docRef = db
                .collection("users")
                .document(uid)
                .collection("incidents")
                .add(incident)
                .await()

            //returns an autogenerated incident document id
            docRef.id

        } catch (e: Exception) {
            throw Exception("Failed to save incident: ${e.message}")
        }
    }

    //get all incidents
    //retrieves all incident records for the user
    suspend fun getIncidents(): List<Incident> {
        val uid = getCurrentUID()

        return try {
            val snapshot = db
                .collection("users")
                .document(uid)
                .collection("incidents")
                .get()
                .await()

            //maps each firestore document to an incident data class
            snapshot.documents.mapNotNull { doc ->
                doc.toObject(Incident::class.java)?.copy(incidentId = doc.id)
            }

        } catch (e: Exception) {
            throw Exception("Failed to retrieve incidents: ${e.message}")
        }
    }

    //get sincle incident
    //retrieves one record by document id
    suspend fun getIncident(incidentId: String): Incident {
        val uid = getCurrentUID()

        return try {
            val doc = db
                .collection("users")
                .document(uid)
                .collection("incidents")
                .document(incidentId)
                .get()
                .await()

            doc.toObject(Incident::class.java)?.copy(incidentId = doc.id)
                ?: throw Exception("Incident not found.")

        } catch (e: Exception) {
            throw Exception("Failed to retrieve incident: ${e.message}")
        }
    }

    //delete incident
    suspend fun deleteIncident(incidentId: String) {
        val uid = getCurrentUID()

        try {
            db
                .collection("users")
                .document(uid)
                .collection("incidents")
                .document(incidentId)
                .delete()
                .await()

        } catch (e: Exception) {
            throw Exception("Failed to delete incident: ${e.message}")
        }
    }

    //updates incident
    suspend fun updateIncident(incidentId: String, updates: Map<String, Any>) {
        val uid = getCurrentUID()

        try {
            db
                .collection("users")
                .document(uid)
                .collection("incidents")
                .document(incidentId)
                .update(updates)
                .await()

        } catch (e: Exception) {
            throw Exception("Failed to update incident: ${e.message}")
        }
    }
}